name: Android Build & Sign

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: /home/runner/android-sdk
  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Decode keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Check Gradle version
      run: ./platforms/android/gradlew --version

    - name: Install dependencies
      run: npm install

    - name: Build Android Release
      run: ./platforms/android/gradlew assembleRelease

    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

    - name: Align APK
      run: |
        zipalign -v -p 4 \
          ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          ./pushtina-game-release.apk

    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: pushtina-game-release.apk
        path: pushtina-game-release.apk

