name: Android Build and Sign

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /home/runner/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK tools
      uses: android-actions/setup-android@v2

    - name: Install required Android SDK packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" \
                   "platforms;android-34" \
                   "build-tools;35.0.0"

    - name: Decode keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

    - name: Install Gradle Wrapper
      run: ./gradlew --version

    - name: Build Release APK
      run: cordova build android --release

    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore release.keystore \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.KEY_ALIAS }}

    - name: Align APK
      run: |
        zipalign -v 4 \
          platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          platforms/android/app/build/outputs/apk/release/app-release.apk

    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: pushtina-release-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
