name: Build and Upload APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools-version: 35.0.1

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install project dependencies
        run: npm install || true

      - name: Add Android platform (if not added)
        run: |
          cordova platform add android || echo "Android platform already added"

      - name: Build Cordova Android Release APK
        run: cordova build android --release

      - name: List build outputs (for debug)
        run: ls -lR platforms/android/app/build/outputs/apk/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
          if-no-files-found: warn
          compression-level: 6
          overwrite: true
