
name: Build and Sign APK

on:
  push:
    branches:
      - main  # Или ветка, в которой хочешь запускать сборку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Decode and save keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install Gradle (wrapper is preferred, but на всякий случай)
      run: sudo apt-get install -y gradle

    - name: Prepare Android platform
      run: |
        cordova platform add android

    - name: Build APK Release
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        cordova build android --release -- --keystore=./my-release-key.jks --storePassword=$KEYSTORE_PASSWORD --alias=$KEY_ALIAS --password=$KEY_PASSWORD

    - name: Upload signed APK
      uses: actions/upload-artifact@v3
      with:
        name: signed-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
