name: Build and Sign Android APK

on:
  push:
    branches:
      - main  # или ветка, с которой будешь запускать сборку
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Install Android SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          # Дополнительно можно установить sdkmanager и прочее, если необходимо

      - name: Decode keystore from base64 and save
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > my-release-key.jks

      - name: Add Android platform
        run: cordova platform add android@latest

      - name: Build Android release
        run: cordova build android --release

      - name: Sign the APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore my-release-key.jks \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            "$KEY_ALIAS"
          
          # Zipalign (путь к zipalign может отличаться, в Ubuntu обычно установлен в Android SDK build-tools)
          # Предположим, что zipalign доступен
          zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk platforms/android/app/build/outputs/apk/release/app-release.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: platforms/android/app/build/outputs/apk/release/app-release.apk
